// Localidades de la provincia de La Rioja, Argentina
// Ordenadas alfabéticamente
export const localidades: string[] = [
    "Aguadita de los Valdez",
    "Aguayo",
    "Aicuña",
    "Aimogasta",
    "Alpasinche",
    "Alto Carrizal",
    "Alto Jagüé",
    "Aminga",
    "Amuschinas",
    "Andolucas",
    "Anguinán",
    "Anillaco",
    "Anjullón",
    "Antinaco",
    "Arauco",
    "Atiles",
    "Bajo Carrizal",
    "Bajo Hondo",
    "Banda Florida",
    "Bañado de los Pantanos",
    "Bella Vista",
    "Campanas",
    "Carrizal",
    "Casa de Piedra",
    "Castro Barros",
    "Catuna",
    "Chañar",
    "Chaupihuasi",
    "Chepes",
    "Chepes Viejo",
    "Chilecito",
    "Chuquis",
    "Colonia Anguinán",
    "Colonia Catinzaco",
    "Colonia Malligasta",
    "Colonia Ortiz de Ocampo",
    "Cuipán",
    "El Barreal",
    "El Cadillo",
    "El Condado",
    "El Durazno",
    "El Portezuelo",
    "El Potrerillo",
    "El Retiro",
    "El Tala",
    "Famatina",
    "Guanchín",
    "Guandacol",
    "Huaco",
    "Jagüé",
    "La Aguadita",
    "La Banda",
    "La Cañada",
    "La Ciénaga",
    "La Gredita",
    "La Jarilla",
    "La Mejicana",
    "La Puntilla",
    "La Rioja",
    "Las Higueras",
    "Las Peñas",
    "Las Talas",
    "Los Colorados",
    "Los Molinos",
    "Los Palacios",
    "Los Sarmientos",
    "Malanzán",
    "Malligasta",
    "Mascasín",
    "Milagro",
    "Nonogasta",
    "Ñoqueve",
    "Olpas",
    "Olta",
    "Pagancillo",
    "Patquía",
    "Pinchas",
    "Pituil",
    "Pozo de la Piedra",
    "Punta de los Llanos",
    "Rivadavia",
    "San Antonio",
    "San Blas",
    "San Blas de los Sauces",
    "San Nicolás",
    "San Pedro",
    "Sanagasta",
    "Santa Cruz",
    "Santa Florentina",
    "Santa Rita de Catuna",
    "Santa Vera Cruz",
    "Sañogasta",
    "Talva",
    "Tama",
    "Talamuyuna",
    "Tilimuqui",
    "Tuizón",
    "Ulapes",
    "Vichigasta",
    "Villa Bustos",
    "Villa Castelli",
    "Villa Mazán",
    "Villa Sanagasta",
    "Villa Unión",
    "Vinchina",
].sort();

// Mapa de cercanía entre localidades principales
export const cercanas: Record<string, string[]> = {
    "La Rioja": ["Sanagasta", "Villa Sanagasta", "Talamuyuna", "Anillaco", "Aminga"],
    "Chilecito": ["Nonogasta", "Malligasta", "Famatina", "Los Sarmientos", "Antinaco", "Pituil", "Anguinán", "Tilimuqui", "Vichigasta", "Sañogasta"],
    "Famatina": ["Chilecito", "Los Sarmientos", "Antinaco", "Pituil", "Alto Carrizal", "Bajo Carrizal", "Carrizal", "Campanas"],
    "Anillaco": ["Aminga", "Chuquis", "La Rioja", "Castro Barros", "Anjullón", "Pinchas"],
    "Aminga": ["Anillaco", "Chuquis", "Castro Barros", "La Aguadita"],
    "Villa Unión": ["Pagancillo", "Guandacol", "Villa Castelli", "Aicuña", "Jagüé"],
    "Vinchina": ["Villa Unión", "Jagüé", "Alto Jagüé", "Guandacol"],
    "Aimogasta": ["Arauco", "Villa Mazán", "Bañado de los Pantanos"],
    "Chepes": ["Patquía", "Punta de los Llanos", "Olta", "Malanzán"],
    "Chamical": ["Chañar", "El Tala", "La Jarilla", "La Cañada", "Bella Vista", "Talva"],
    "Sanagasta": ["La Rioja", "Villa Sanagasta", "El Durazno", "Las Peñas", "El Portezuelo"],
    "San Blas de los Sauces": ["Aguayo", "Alpasinche", "Andolucas", "Cuipán", "Huaco", "Los Palacios"],
    "Patquía": ["Chepes", "Rivadavia", "Los Colorados", "Villa Bustos"],
    "Guandacol": ["Villa Unión", "Pagancillo", "Vinchina"],
};

export function getCercanas(loc: string): string[] {
    if (cercanas[loc]) return cercanas[loc];
    // Fallback: devolver localidades conocidas
    return ["Chilecito", "La Rioja", "Villa Unión", "Famatina", "Anillaco"].filter((l) => l !== loc);
}